---

language: c
compiler: gcc

dist: trusty
sudo: required

before_install:
  - sudo apt-get update
  - sudo make get-dep-debian-all

install:
  - make all TRAVIS=1
  - sudo make install-all

script:
  - make check TRAVIS=1

notifications:
  email: false
