---

language: c
compiler: gcc

dist: trusty
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - make get-dep-debian-all

install:
  - make build-dynamic-lib TRAVIS=1
  - make install-all

script: true

notifications:
  email: false
