---

language: c
compiler: gcc

sudo: required

before_install:
  - make get-dep-debian-all

install:
  - make build-dynamic-lib TRAVIS=1
  - make install-all

script: true

notifications:
  email: false
